export const data = [
    {
      dat: "September 2014 - June 2016",
      text: "Studies BS. Mechatronics, robotics and automation technology.",
      place: "FAU Erlangen, Germany",
    },
    {
      dat: "June 2016 - September 2017",
      text: "Founder NANDA MESSENGER (Chat, Banking, Mobile Money,Story) .",
      place: "Nürnberg, Germany",
      toDo: [
        "Watermelon DB for local data storage, backup as sqlite file on google drive",
        "Authentication microservices",
        "Notifications microservices",
        "Messaging and Chat",
        "Banking",
        "Video chat with WEBRTC",
        "Video and image editing with face detection and filter application",
      ],
      stacks: [
        "NodeJs",
        "React-Native",
        "Watermelon DB",
        "Sqlite",
        "Git",
        "RUST (WebRTC)",
        "Java android for some native components",
        "Swift for some native components ",
      ],
      tools: ["Github", "Slack"],
    },
    {
      dat: "September 2017 - August 2018",
      text: "Studies BS. Mechatronics, robotics and automation technology.",
      place: "Technische Hochschule Nürnberg, Germany",
    },
    {
      dat: "August 2018 - June 2019",
      text: "Freeelancer JQUERY / ReactJS / PHP / Python by Glancy3D (Glancy 3D provides the first artificial intelligence that predicts how your Client are going to perceive your product) ",
      place: "Paris ,France",
      toDo: [
        "Web scraping of product images from the web for model training",
        "Modernise the homepage built with Jquery",
        "Migrating the user dashboard from Jquery to ReactJS",
        "Create an authentication and billing system",
        "3D product visualization with ThreeJS",
      ],
      stacks: [
        "JQUERY",
        "PHP",
        "ReactJS",
        "Python",
        "THREEJS",
        "Motion UI",
        "Git",
      ],
      tools: ["Github", "GitLab", "Slack"],
    },
    {
      dat: "July 2019 - December 2019",
      text: "Freelancer NODEJS/ ReactJS / React-Native by PostExo",
      place: " Paris, France",
      toDo: [
        "Architecture for the NodeJS backend",
        "Build the Authentication microservices",
        "Build the notifications microservices",
        "Frontend help on the user and teacher dashboard",
      ],
      stacks: [
        "NodeJS",
        "ReactJs",
        "Semantic UI",
        "React-native",
        "Socket.IO",
        "MySql",
        "Redux",
        "Git",
      ],
      tools: ["Gitlab", "Slack", "Illustrator", "Blender"],
      note: [
        "RESTFUL API",
        "Integration & Unit test with JEST",
        "Microservices architecture (sync architecture) ",
      ],
    },
    {
      dat: "Januar 2020 - May 2020",
      text: "Freelancer ReactJS / React-Native (frontend) by OMIO",
      place: "Berlin, Germany ",
      toDo: [
        "Creation of monitoring software to monitor servers, websites and services",
        "Automated notification of problems via SMS and email",
        // "Parallel job queues for automated checks",
      ],
      stacks: [
        "NextJS",
        "NodeJS",
        "Redis",
        "Socket.IO",
        // "Kue by Redis",
        "Styled-components",
        "Bootstrap",
        "Typescript",
      ],
      tools: ["Github", "Zoom", "Yarn"],
    },

    {
        dat: "June 2020 - March 2022",
        text: "Lead developer of Gardlist",
        place: "Paris, France",
        toDo: [
          "Design the logo",
          "Design the  Help and Admin Web-application",
          "Design of the client and partner web application",
          "Creation of an admin panel to monitor servers and services, manage the database and user access, review submitted documents, complete user profiles. ",
          "Create a help subdomain with articles and good search function with a headless CMS",
          "Setting up a Client subdomain with the following functions: Chat, e-signature of contracts, automatic generation of PDF contracts before and after signature, search for job offers and trainings.",
          "Building a React Native app with all functions of the Client subdomain",
          "Set up a partner subdomain with the same function as the Client subdomain above and additionally dynamically fill in each contract template with user data when imported into the app, create job offers and trainings. ",
          "Autogenerates an image for each job and formation that summarises the offer, can be used for SEO purposes and for social media share ",
          "Creation of a partner dashboard to monitor job vacancy and staffing statistics",
          "Receive and respond to quotation requests with an automatically generated PDF",
          "The backend consists of 6 isolated microservices (auth, messaging, emailing microservice, notifications, jobs, formations) .",
          "Hooks for front-end cache and Redis for back-end cache",
          "All projects are extremely typified and isolated",
        ],
        stacks: [
          "NodeJS",
          "NextJS",
          "Styled-components",
          "Bootstrap",
          "Typescript",
          "SOCKET.IO",
          "AWS S3",
          "Headless CMS Strapi",
          "Puppeteer JS",
          "CSS",
          "React-Native",
          "Expo",
          "ReactJS",
          "Redux",
          "MongoDB",
          "Git",
          "Redis",
          "Sass",
          "Amazon cloudFront",
          "Webpack",
        ],
        note: [
          "RESTFUL API",
          "Integration & Unit test with JEST",
          "Microservices architecture (event-based architectute with NATS as event Broker)",
        ],
        tools: [
          "Figma",
          "Adobe XD",
          "Illustrator",
          "Blender",
          "Github",
          "react-lottie",
          "VS-Code",
          "Yarn",
          "Slack",
          "Google Meet",
          "Docker",
          "Kubenertes",
          "Skaffold",
        ],
      },
   
    
  ];
  